name: Run min numpy tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
    - name: Install osmesa
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install libosmesa6-dev
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Setup yt_idv
      run: python -m pip install -e .[test,minimal]
    - name: Run Tests
      env:
          PYOPENGL_PLATFORM: osmesa
      run: pytest --html=report.html --self-contained-html
    - uses: actions/upload-artifact@v3
      name: Upload pytest report
      with:
        name: pytest-report
        path: report.html
